### ISSUE TITLE
Script nao funciona

### ISSUE THREAD

**Issue by marcianovc** [luisfeliperm/mikrotik-failover-two-wan#2]
Descomentei todos os logs do script, mas aparece somente o "Iniciando Script" e nao mostra mais nenhum log, ou seja nao ta funcionando ja que mais nenhum log aparece

**Comment by luisfeliperm** [comment]
Olá, acabei de corrigir e atualizar no repositorio.
O erro ocorria quando o RouterOS reiniciava, fazendo com que uma variavel global usada no script para indicar se ele estava em execução, permanecesse existente e com o status anterior ao reboot, dessa forma o script entendia que ele já estava iniciado. Então pra evitar problemas eu removi esse recurso que impedia multiplas execuções do script, futuramente eu adiciono da  forma correta.

**Comment by marcianovc** [comment]
Boa, agora deu certo obrigado 👍
